---
# tasks file for auditd

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost
  module_defaults:
    ansible.builtin.assert:
      quiet: yes
  tags:
    - assert_parameters

- name: Install requirements
  ansible.builtin.package:
    name: "{{ ['bash'] + auditd_packages | list }}"
    state: present

- name: "Create directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ auditd_config_directory }}"
    - "{{ auditd_config_directory }}/rules.d"

- name: Configure auditd
  ansible.builtin.template:
    src: "{{ auditd_config_file }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - Restart auditd

- name: Place custom.rules
  ansible.builtin.template:
    src: custom.rules.j2
    dest: "{{ auditd_config_directory }}/rules.d/custom.rules"
    mode: "0640"
  notify:
    - Run augenrules
  when:
    - auditd_manage_rules

- name: Start and enable auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: started
    enabled: yes
